# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6438b9e71b7113fcf52431110a38cf0b86d6a1cf56b89ceefa7f4ce1fa7affe4e7d43417b18631fa45e3692730e8c0c86d1b86b891dfab2f0e43b866c191a4c

test:
  secret_key_base: 2ade7a15c9f5ce36e7a0be6df6d6e34024a5d2eace35f676d0d3fa162a7b2a358f9e61fc62e3ae23b097ec7fa4e12508824d986d68c64be104cce1b78c203221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
